# Generated by Django 5.2.4 on 2026-02-13 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_username', models.CharField(max_length=100, unique=True)),
                ('github_id', models.IntegerField(blank=True, null=True)),
                ('avatar_url', models.URLField(blank=True)),
                ('html_url', models.URLField(blank=True)),
                ('bio', models.TextField(blank=True)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('blog', models.URLField(blank=True)),
                ('public_repos', models.IntegerField(default=0)),
                ('public_gists', models.IntegerField(default=0)),
                ('followers', models.IntegerField(default=0)),
                ('following', models.IntegerField(default=0)),
                ('total_contributions', models.IntegerField(default=0)),
                ('total_commits', models.IntegerField(default=0)),
                ('total_prs', models.IntegerField(default=0)),
                ('total_issues', models.IntegerField(default=0)),
                ('total_stars_received', models.IntegerField(default=0)),
                ('top_languages', models.JSONField(blank=True, default=list)),
                ('top_repos', models.JSONField(blank=True, default=list)),
                ('access_token', models.CharField(blank=True, max_length=255)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('github_created_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='github_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'GitHub Profile',
                'verbose_name_plural': 'GitHub Profiles',
            },
        ),
    ]
