# Generated by Django 5.2.11 on 2026-02-12 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeforcesProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cf_handle', models.CharField(max_length=100, unique=True)),
                ('cf_rating', models.IntegerField(default=0)),
                ('cf_max_rating', models.IntegerField(default=0)),
                ('cf_rank', models.CharField(default='Newbie', max_length=50)),
                ('cf_max_rank', models.CharField(default='Newbie', max_length=50)),
                ('cf_avatar', models.URLField(blank=True)),
                ('cf_contribution', models.IntegerField(default=0)),
                ('cf_friend_count', models.IntegerField(default=0)),
                ('problems_solved', models.IntegerField(default=0)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cf_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
