# Generated by Django 5.2.11 on 2026-02-12 19:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('code_snippet', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('code_snippet', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('type', models.CharField(choices=[('MANUAL', 'Manual'), ('GITHUB_COMMIT', 'GitHub Commit'), ('LEETCODE_SOLVE', 'LeetCode Solve'), ('MILESTONE', 'Milestone')], default='MANUAL', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('RESPECT', 'Respect'), ('FIRE', 'Fire'), ('BUG', 'Bug')], max_length=20)),
            ],
        ),
    ]
