# Generated by Django 5.2.11 on 2026-02-13 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('GITHUB_COMMIT', 'GitHub Commit'), ('CODEFORCES_SOLVE', 'Codeforces Solve'), ('MILESTONE', 'Milestone')], default='MANUAL', max_length=20),
        ),
    ]
